-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgOLFYtRgpGTbtgaSB
SnQ0k4xH6jidsBdtB3TQzH/dinmgCgYIKoZIzj0DAQehRANCAATjH0mLKq6IYSi9
DZ+li7EEep6cA7kvf7girykqCsXWsM2qxF2Y1lMeKTXbq85s+pzEDAPBd+j3EgN8
bWKJpys1
-----END PRIVATE KEY-----