-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgUffez3eIxh4EbOIN
ux7JoftnXgF/zK/nHjFQub5hcdqgCgYIKoZIzj0DAQehRANCAAS2es7Cuj2BfnqK
4eH7qlD/6IcsBiR9CIOA0SrSNNiIefDfejA4ZyPUkeLrtgC627dkchi6BDXT585k
TzAPJPxj
-----END PRIVATE KEY-----