-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgALTPg5GSpMelOfwH
IbpPLartB8DvdUw5DzxSxDXELoWgCgYIKoZIzj0DAQehRANCAASQblIpfhjRy467
sk/pby1ks7z/bStDG44C6ncZDdmMCf2edV8cNJ8v/GXOIsVjRiwgH+tjyVF3w0I8
JqblnDUg
-----END PRIVATE KEY-----