# Apple Developer Account Configuration
APPLE_ISSUER_ID=32837406-47b5-491a-87ac-1dc1ca272bf7
APPLE_KEY_ID=J6RS6X65RY
APPLE_ASC_PROVIDER=52RYPUFXRT
# 注意：请将您的 .p8 私钥文件命名为 AuthKey_<APPLE_KEY_ID>.p8 
# 并放置在项目根目录下的 private_keys/ 文件夹中。