# Apple Developer Account Configuration
APPLE_ISSUER_ID=xxxx(App Store Connect API Issuer ID)
APPLE_KEY_ID=xxxx(App Store Connect API Key ID)
APPLE_ASC_PROVIDER=xxxx(Team ID, 可选/若有多个团队则保留)
# 注意：请将您的 .p8 私钥文件命名为 AuthKey_<APPLE_KEY_ID>.p8 
# 并放置在项目根目录下的 private_keys/ 文件夹中。